<?php
include_once(SITE_PATH ."/core/Helper.php");
$lang=LOCALE;

?>
<div class="well form-inline" >
    <div style="float:left;">

        <a class="btn btn-success" href="<?=$this->registry['router']->url_admin($params = array(
								'controller' => $page,
								'action' => 'news',
								'assort' => $assort,
								'lang'	=> $lang														
														))?>"><i class="icon-plus icon-white"></i> <?=$translate->translate('Add post')?> </a>		
    </div>
    
</div>

<?php if (!isset($records) || !count($records)): ?>
    <h4><?=$translate->translate('Not records')?></h4>
<?php else: ?>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th><a href="<?=$this->registry['router']->url_admin( $params = array(
																		'controller' => $page,
																		'action' => 'index',
																		'lang'	=> $lang,
																		'sort' => 'id',
																		'by' => $this->registry['helper']->sortdirect('id', $assort['sort'], $assort['by'])
																	)
														)?>">
						<i class="<?=$this->registry['helper']->sortparam ('id', $assort['sort'], $assort['by'])?>"></i> <?=$translate->translate('Id')?>
					</a>
				</th>
                
				<th><a href="<?=$this->registry['router']->url_admin( $params = array(
																		'controller' => $page,
																		'action' => 'index',
																		'lang'	=> $lang,
																		'sort' => 'title',
																		'by' => $this->registry['helper']->sortdirect('title', $assort['sort'], $assort['by'])
																	)
														)?>">
						<i class="<?=$this->registry['helper']->sortparam ('title', $assort['sort'], $assort['by'])?>"></i> 
						<?=$translate->translate('Title')?>
					</a>
				</th>
                
				<th><a href="<?=$this->registry['router']->url_admin( $params = array(
																		'controller' => $page,
																		'action' => 'index', 
																		'sort' => 'published_at',
																		'lang'	=> $lang,
																		'by' => $this->registry['helper']->sortdirect('published_at', $assort['sort'], $assort['by'])
																	)
														)?>">
						<i class="<?=$this->registry['helper']->sortparam ('published_at', $assort['sort'], $assort['by'])?>"></i>
						<?=$translate->translate('Published')?>
					</a>
				</th>
                				
				<th><?=$translate->translate("Active")?></td>					
												
				<th width="300"><?=$translate->translate('Actions')?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($records as $record): ?>
				<tr>
			
					<td><?=$record->id?></td>
					<td><?=$record->title?></td>					
					<td><?= date_frommysql($record->published_at)?></td>										
					<td style="text-align:center;"><?=sprintf('<i class="icon-%s"></i>', $record->published ? 'ok' : 'remove')?></td>					
		
					<td style="text-align:center;">
			

                        <div class="btn-group">
                            <a class="btn" href="<?=$this->registry['router']->url_admin($params = array(
								'controller' => $page,
								'action' => 'edit', 
								'cid' => $record->id,
								'assort' => $assort,
								'lang' => $lang
							))?>" title="<?=$translate->translate("Edit")?>"><i class="icon-edit"></i></a>

						<a class="btn" href="<?=$this->registry['router']->url_admin( $params = array(
								'controller' => $page,
								'action' => 'show', 
								'cid' => $record->id,
								'current' => $record->published,
								'lang'	=> $lang,
								'assort' => $assort
							))?>" title="<?=$translate->translate("Active")?>"><i class="icon-eye-open"></i></a>	

							<a class="btn" href="<?=$this->registry['router']->url_admin( $params = array(
								'controller' => $page,
								'action' => 'ccopy', 
								'cid' => $record->id,
								'lang'	=> $lang,
								'assort' => $assort
							))?>" title="<?=$translate->translate("Copy")?>"><i class="icon-file"></i></a>		
							
						<a class="btn btn-danger confirm-delete" 
							message="<?=$translate->translate("Are you sure you want to delete the record?")?>"
                            href="<?=$this->registry['router']->url_admin($params = array(
								'controller' => $page,
								'action' => 'delete', 
								'cid' => $record->id,
								'lang'	=> $lang,
								'assort' => $assort
							))?>" title="<?=$translate->translate("Delete")?>"><i class="icon-trash icon-white"></i></a>							
						</div>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<div class="top_options">
		<?php require_once 'partials/paginator_admin.phtml';?>		
	</div>	 	
<?php endif; ?>

