
 <?php isset($_SESSION['consultant']['title'])?$img='Ozernov.jpg' :$img='';
  
 ?>




<div class="container-fluid">
        <div class="row " >
            <div class="col-lg-12">
                <h1 class="page-header">
                    Hi! Hi!
                    
                    
                   <img src="<?=REAL_IMAGE_PATH.$img ?>" width="200"  class="thumbnail"> 
                    
                    
                </h1>
            </div>
        </div>
</div>        
