
<base href="<?=BASEURL?>" />

<meta content="NOINDEX, NOFOLLOW" name="ROBOTS">


<link rel="stylesheet" href="css/bootstrap-responsive.css">
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/admin.css">


<script type="text/javascript" src="js/jquery.js"></script> 
<script type="text/javascript" src="js/bootstrap.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<script type="text/javascript" src="js/chosen/chosen.jquery.js"></script>
<script type="text/javascript" src="js/tinymce/jquery.tinymce.js"></script>
<script type="text/javascript" src="js/admin.js"></script>

<link rel="stylesheet" href="js/chosen/chosen.css">
<link rel="stylesheet" href="js/chosen/chosen-bootstrap.css">
<link rel="stylesheet" href="js/chosen/chosen.chzn.css">


<title>Панель администратора / Главное меню</title>

<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html;charset=utf-8"/> 
<link type="image/x-icon" href="" rel="icon">

<!--[if IE]>
<link type="image/x-icon" href="images/favicon.ico');?>" rel="icon">
<![endif]-->

<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
