 

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href=""><img src="../../admin/assets/imagesuser/LogoOrieco.png" width="70px;">Панель администратора</a>
            <div class="btn-group pull-right">
                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-user"></i>
                    <?=isset($_SESSION['consultant']['title'])?$_SESSION['consultant']['title']:'';?>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?=$this->registry['router']->url_admin( $params = array('controller' => 'login',
																'action' => 'logout', 
																)
														)?>">Log Out</a></li>
                </ul>
            </div>	
            <div class="btn-group pull-right">
                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                    <?=$this->registry['sessvar']->langs[$this->registry['sessvar']->getCurrentLocale()]?>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
					<?php foreach ($this->registry['sessvar']->langs as $key => $value) { ?>
						<li><a href="<?=$this->registry['router']->url_admin( $params = array(
									'controller' => 'index',
									'action' => 'index', 
									'lang' => $key
								)
							)?>"><?=$value?></a></li>
					<?php } ?>
                </ul>
            </div>				
        </div>
    </div>
</div>
<div id="fixed"></div>